### ISSUE TITLE
Planet Scope imagery access

### ISSUE THREAD

**Issue by SoutoPaola** [ydoherty/CoastSat.PlanetScope#1]
Hi!

First of all, thank you for this program.

This is not a question about the program (still stuck in a previous step), sorry about that. I would like to know how to access to the Planet Scope imagery. I have read that it must be downloaded through the QGIS plugin. Time ago I downloaded this plugin and made a trial account, but it has expired. I need to perform a formal request to be able to download the images?

Thank you in advance, best wishes

Paola

**Comment by ydoherty** [comment]
Hi @SoutoPaola, 

No problem at all! For research purposes you can apply for a Basic license which lets you download 5,000km^2 per month.
   - https://www.planet.com/markets/education-and-research/

But yes, you will need to apply formally. Annoyingly it took around a month for my application to be approved but it may be faster now. Once you have the license, you should be able to login using the QGIS plugin and download as per the readme instructions. For commercial on non-research purposes you may need to contact Planet. 

Hope it all goes well!

Cheers, 
Yarran
