### ISSUE TITLE
No shoreline

### ISSUE THREAD

**Issue by ReggieRocket** [ydoherty/CoastSat.PlanetScope#10]
Hi Yarran,

This such a great tool! I'm excited to measure the accuracy of shorelines compared to CoastSat. 

Something interesting is happening with my dataset. Shorelines are only being drawn on about 1/4 of all the good quality images. I attached an example of this. Something I'm noticing is that there isn't many sand pixels in the classified image of the whole dataset. Do you think that's causing it?

Let me know what other information would be helpful!

Thanks,
Shannon 

![2016-12-28 15_01_39 016- PS2 shoreline plot](https://user-images.githubusercontent.com/21685436/217934352-978f9d04-b386-4ebd-a5b4-72cb4cf81906.png)
![2017-01-28 15_02_21 017- PS2 shoreline plot](https://user-images.githubusercontent.com/21685436/217934454-c06c8c80-4be3-40bc-a6a3-d8bf01c2c4c5.png)
![2016-10-30 14_59_06 016- PS2 shoreline plot](https://user-images.githubusercontent.com/21685436/217934470-0c05b4cf-2df7-4a82-9b60-4bbbb12b356b.png)
![2016-12-23 15_00_59 016- PS2 shoreline plot](https://user-images.githubusercontent.com/21685436/217934490-f6ecce42-3dd0-4082-b5d3-4b31b1d95fbf.png)

**Comment by ReggieRocket** [comment]
This was happening at another site as well. That site has less images and a much quicker processing time, so I retrained the classifier and it is doing well picking out the different classes, but still there is no shoreline.
![2018-11-18 17_46_24 2018 PS2 shoreline plot](https://user-images.githubusercontent.com/21685436/218491144-de6ad5f4-e018-44a6-9e53-ec50089f9d5e.png)

**Comment by ydoherty** [comment]
Hi Shannon,

Apologies for the delay, I’ve had a busy week at work and upkeep this git
in my free time now. For the first email I would say re-training the
classifier would be the first thing to check. Seems like you’ve done that
for the second email however .

Other setting to check would be:

 - have you drawn the reference shoreline close enough to the expected
shoreline location? And if so is the max_dist_ref buffer distance from the
ref shoreline enough? The default of 75m should work in almost all cases
though

- from you images, it looks like you’re downloading a small section of
beach. The min_beach_area (in m2) setting may be impacting the shoreline
drawing. If the number of pixels classified as sand is less than this area,
it won’t draw a shoreline. This is for sites where there may be back beach
dunes you don’t want to contour. Try dropping this number significantly and
seeing if it works (maybe start with 100 then work up if it works)

- Similar to the above, if you’ve only got a small image, you’ll also need
to drop the min_length_shoreline down from the default 500m. All contours
less than this length are dropped. Again try dropping this significantly
then work up from there if it’s works (starts around 50m maybe)

If those don’t work there are some further settings you could play around
with in the …coastsat_ps/data_import.py file. Although these settings
should be a last resort as they change how bits of code run.

Let me know if those work!

Cheers,
Yarran
