### ISSUE TITLE
Mask extraction

### ISSUE THREAD

**Issue by Jand607** [ydoherty/CoastSat.PlanetScope#22]
Kia ora from NZ,

@ydoherty thanks for your help a couple of weeks ago. I am having a new issue when extracting masks from the images:
![image](https://github.com/user-attachments/assets/4129063b-b0ba-4108-a3ae-de8fa4773975)

This doesn't make sense, because the in_place argument is meant to be there!

Cheers
Jack

**Comment by ydoherty** [comment]
Hi Jack, 

Apologies for the slow response, I somehow missed this. 

It looks like you are probably using an updated (or older) version of skimage (which is where morphology.remove_small_objects comes from). If the maintainers of the repo updated and modified the remove_small_objects  function, it may no longer accept the in_place input. 

In my recent round of CoastSat.PlanetScope updates last month I added a new set of .yml environment installation files. I would try create a new environment using mamba and the new installation files and hopefully that will fix your package version problems. I also updated the readme content to better explain environment installation. 

Hopefully that works for you. 

Cheers, 
Yarran
