### ISSUE TITLE
PlanetScope Imagery settings

### ISSUE THREAD

**Issue by JanTiede** [ydoherty/CoastSat.PlanetScope#3]
Dear Yarran,
thank you for your work, it is very impressive.

I wondered which type of images and settings you used for the download of the PlanetScope imagery. If you used the rectified assets by PlanetScope and if yes, which ones. It seems when I run the scripts the endings of the filenames the script is looking for are not matching the ones I downloaded. Can you help?

Another small issue: when I download the package from Github as a windows user and unzip it, the folder name by default is "CoastSat.PlanetScope-main" causing the script to fail when it checks if the working folder name is "CoastSat.PlanetScope". Maybe worth mentioning this in your readme.

Cheers
Jan

**Comment by ydoherty** [comment]
Hi Jan, 

I downloaded my images in QGIS using the PlanetScope plug-in and the clip to AOI setting selected. It also works downloaded from the PS website. You'll want 4-band multispectral Analytic Ortho scene images. I'll update these details in the readme soon, thanks for the feedback! Try again with the file type mentioned above and hopefully it works. If not let me know what the filenames look like and any error messages you get. 

Ah yep, I've mainly done the development on mac so haven't come across bugs like that. I'll tweak the code to cope with the "-main" extension soon. 

Regards, 
Yarran
