### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by awkis23** [ydoherty/CoastSat.PlanetScope#5]
Dear Yarran,
thank you for your great work. It's very impressive.

Actually, I'm new to this field and don't know how to work with the CoastSat.PlanetScope.
Before I work with the CoastSat https://github.com/kvos/CoastSat, and it was successful because the procedures are very clear to understand and explained step by step.
I'm not familiar with coding so that I have difficulties running the CoastSat.PlanetScope.
Could you mind to make the procedure step by step? If you don't mind.
Thank you for your kind help.

**Comment by ydoherty** [comment]
Hi, 

Thanks for checking it out and I'm interested to hear any feedback or comments. 

Similar to Kilian's CoastSat structure, the PlanetScope CoastSat_PS.py file is structured into 6 sections covering settings, pre-processing, shoreline extraction, error detection and then short sections on processing and viewing outputs. 

I'd suggest fully reading through the readme to try understand the workflow and sections before running each section of the code. 

Unfortunately I am no longer actively working on this project so I am providing maintenance and support in my spare time. If you have any specific questions I am happy to answer them, but I doubt I will have the time to do any major re-structuring any time soon. 

Regards, 
Yarran
