### ISSUE TITLE
Has this been published yet? 

### ISSUE THREAD

**Issue by jacobjcastaneda** [ydoherty/CoastSat.PlanetScope#6]
Hey again,

If this has been published I cant seem to find it. Could you please update me on it and if its released possibly share it here?

jacob

**Comment by ydoherty** [comment]
Hey Jacob, 

Unfortunately there have been a few delays as I've been full time on a few other projects. I'm checking in with colleagues to see if I can give you a better eta or when a pre-print may be ready.

Apologies for the delays. 

Cheers, 
Yarran

**Comment by ydoherty** [comment]
Hi Jacob, a touch later than expected but the pre-print is out now!

https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4052360

I'm in the process of reviewing comments at the moment so hopefully the final manuscript should be submitted and published in the near future. 
 
- Yarran
