### ISSUE TITLE
No Planet Download Files for Example?

### ISSUE THREAD

**Issue by seamuslo** [ydoherty/CoastSat.PlanetScope#9]
Hi @kvos 
 @ydoherty , thanks again for developing this great software. 
 
 I am attempting to run the Planetscope example, but I get the error: "FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\testing_cmd\\Desktop\\CoastSat.PlanetScope\\Narrabeen_images_PSScene4Band\\files'"
 
 I think its looking for the Planet download files (TIFFs, XMLs, etc.), but it can't find them. 
 
 I looked around on the github, but didn't see these files either. Could you direct me to them or let me know where else I could find them? I'd really like to run the example

**Comment by ydoherty** [comment]
Hi @seamuslo, apologies for the delayed response. The CoastSat PlanetScope repo unfortunately does not have any provided example imagery as it would breach the Planet research license agreement. To run the example it requires the user to manually download a set of images from either Planet Explorer of the QGIS plugin (this is what I use). Once you have downloaded a set of images, update the 'downloads_folder' setting with the relevant folder details and it should run!
